/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    fontFamily: {
      sans: ["LatoRegular"]
    },
    extend: {},
    colors: {
      'surface': '#FEF7FF',
      'surface-trans': 'rgba(254,247,255,0.5)',
      'surface-trans2': 'rgba(254,247,255,0.9)',
      'surface-on': '#1D1B20',
      'primary': '#6750A4',
      'primary-on': '#FFFFFF',
      'primary-container': '#EADDFF',
      'primary-container-on': '#4F378B',
      'secondary': '#625B71',
      'secondary-on': '#FFFFFF',
      'secondary-container': '#E8DEF8',
      'secondary-container-on': '#4A4458',
      'tertiary': '#7D5260',
      'tertiary-on': '#FFFFFF',
      'tertiary-container': '#FFD8E4',
      'tertiary-container-on': '#633B48',
      'error': '#B3261E',
      'warning': '#EAC272',
      'error-on': '#FFFFFF',
      'error-container': '#F9DEDC',
      'error-container-on': '#8C1D18',
      'outline': '#79747E',
      'outline-variant': '#79747E',
      'dark-surface': '#141218',
      'dark-surface-trans': 'rgba(20,18,24,0.5)',
      'dark-surface-trans2': 'rgba(20,18,24,0.9)',
      'dark-surface-on': '#E6E0E9',
      'dark-primary': '#D0BCFF',
      'dark-primary-on': '#381E72',
      'dark-primary-container': '#4F378B',
      'dark-primary-container-on': '#EADDFF',
      'dark-secondary': '#CCC2DC',
      'dark-secondary-on': '#332D41',
      'dark-secondary-container': '#4A4458',
      'dark-secondary-container-on': '#E8DEF8',
      'dark-tertiary': '#EFB8C8',
      'dark-tertiary-on': '#492532',
      'dark-tertiary-container': '#633B48',
      'dark-tertiary-container-on': '#FFD8E4',
      'dark-error': '#F2B8B5',
      'dark-error-on': '#601410',
      'dark-error-container': '#8C1D18',
      'dark-error-container-on': '#F9DEDC',
      'dark-outline': '#938F99',
      'dark-outline-variant': '#49454F',
      'dark-shadow': '#222222',
      'gradient1': '#3b82f6',
      'gradient2': '#ac33ea',
      'gradient3':  '#d987fa',
      'dark-gradient1': '#142f57',
      'dark-gradient2': '#4b1468',
      'dark-gradient3':  '#4e3459'

    },
  },
  plugins: [],
  darkMode: 'media'
}
